//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolConsole.SchoolServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolServiceReference.ISchoolService_now")]
    public interface ISchoolService_now {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/getCourses", ReplyAction="http://tempuri.org/ISchoolService_now/getCoursesResponse")]
        SchoolServiceLibrary.Course[] getCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/getCourses", ReplyAction="http://tempuri.org/ISchoolService_now/getCoursesResponse")]
        System.Threading.Tasks.Task<SchoolServiceLibrary.Course[]> getCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/getStudents", ReplyAction="http://tempuri.org/ISchoolService_now/getStudentsResponse")]
        SchoolServiceLibrary.Student[] getStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/getStudents", ReplyAction="http://tempuri.org/ISchoolService_now/getStudentsResponse")]
        System.Threading.Tasks.Task<SchoolServiceLibrary.Student[]> getStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/getTeachers", ReplyAction="http://tempuri.org/ISchoolService_now/getTeachersResponse")]
        SchoolServiceLibrary.Teacher[] getTeachers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/getTeachers", ReplyAction="http://tempuri.org/ISchoolService_now/getTeachersResponse")]
        System.Threading.Tasks.Task<SchoolServiceLibrary.Teacher[]> getTeachersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/addCourse", ReplyAction="http://tempuri.org/ISchoolService_now/addCourseResponse")]
        void addCourse(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/addCourse", ReplyAction="http://tempuri.org/ISchoolService_now/addCourseResponse")]
        System.Threading.Tasks.Task addCourseAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/addStudent", ReplyAction="http://tempuri.org/ISchoolService_now/addStudentResponse")]
        void addStudent(string firstname, string lastname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/addStudent", ReplyAction="http://tempuri.org/ISchoolService_now/addStudentResponse")]
        System.Threading.Tasks.Task addStudentAsync(string firstname, string lastname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/addTeacher", ReplyAction="http://tempuri.org/ISchoolService_now/addTeacherResponse")]
        void addTeacher(string firstname, string lastname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService_now/addTeacher", ReplyAction="http://tempuri.org/ISchoolService_now/addTeacherResponse")]
        System.Threading.Tasks.Task addTeacherAsync(string firstname, string lastname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchoolService_nowChannel : SchoolConsole.SchoolServiceReference.ISchoolService_now, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolService_nowClient : System.ServiceModel.ClientBase<SchoolConsole.SchoolServiceReference.ISchoolService_now>, SchoolConsole.SchoolServiceReference.ISchoolService_now {
        
        public SchoolService_nowClient() {
        }
        
        public SchoolService_nowClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolService_nowClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolService_nowClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolService_nowClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SchoolServiceLibrary.Course[] getCourses() {
            return base.Channel.getCourses();
        }
        
        public System.Threading.Tasks.Task<SchoolServiceLibrary.Course[]> getCoursesAsync() {
            return base.Channel.getCoursesAsync();
        }
        
        public SchoolServiceLibrary.Student[] getStudents() {
            return base.Channel.getStudents();
        }
        
        public System.Threading.Tasks.Task<SchoolServiceLibrary.Student[]> getStudentsAsync() {
            return base.Channel.getStudentsAsync();
        }
        
        public SchoolServiceLibrary.Teacher[] getTeachers() {
            return base.Channel.getTeachers();
        }
        
        public System.Threading.Tasks.Task<SchoolServiceLibrary.Teacher[]> getTeachersAsync() {
            return base.Channel.getTeachersAsync();
        }
        
        public void addCourse(string name) {
            base.Channel.addCourse(name);
        }
        
        public System.Threading.Tasks.Task addCourseAsync(string name) {
            return base.Channel.addCourseAsync(name);
        }
        
        public void addStudent(string firstname, string lastname) {
            base.Channel.addStudent(firstname, lastname);
        }
        
        public System.Threading.Tasks.Task addStudentAsync(string firstname, string lastname) {
            return base.Channel.addStudentAsync(firstname, lastname);
        }
        
        public void addTeacher(string firstname, string lastname) {
            base.Channel.addTeacher(firstname, lastname);
        }
        
        public System.Threading.Tasks.Task addTeacherAsync(string firstname, string lastname) {
            return base.Channel.addTeacherAsync(firstname, lastname);
        }
    }
}
